version: 0.1

phases:
    pre_build:
        commands:
            - "mkdir site-packages"
            - "pip install --target=site-packages --ignore-installed -r requirements.txt"

artifacts:
    files:
        - "ddb_ttl_provider.py"
        - "site-packages/**/*"